server:
  port: 8079
spring:
  application:
    name: gateway
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wrq
    username: root
    password: Wangriqing0324
  redis:
    host: 127.0.0.1
    port: 6379
  # Nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.8.128:8848
        namespace: 7658086a-6d49-4bf7-905f-62c2f014eeaa
        enabled: true
    gateway:
      routes:
        - id: toContent
          uri: lb://content
          predicates:
            - Path=/content/**
        - id: toMedia
          uri: lb://media
          predicates:
            - Path=/media/**


# Mybatis配置
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml   # 指定resource目录下的XxxMapper配置文件
  type-aliases-package: wrq.rotation.model.po   # 简化resultType中的po类名
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 配置Mybatis的日志
    map-underscore-to-camel-case: true    # 支持数据表字段下划线与驼峰命名的转换
